### ISSUE TITLE
Where is "EoT.mk"?

### ISSUE THREAD

**Issue by WeichenLi** [EyesOfThings/Software#2]
I build [all of libraries](https://github.com/EyesOfThings/Software/tree/master/Platform%20Software/myriad/libs/leon), I can find these libraries in `mdk/packages/EoT`.     
Then I try to make [`OpenCV_examples`](https://github.com/EyesOfThings/Software/tree/master/Platform%20Software/myriad/apps/OpenCV_examples), but don't find `EoT.mk`.    
Please update it.
Thanks

**Comment by odeniz** [comment]
Dear WeichenLi,

We're glad that you are using the code. For EoT support please see in this page: http://eyesofthings.eu/?page_id=1579

Thanks,
Oscar
